### PR TITLE
Added "threats" field in the parser

### PR DESCRIPTION
**Pull request by sambhrant-metron**
# PR Details

This is Sumo Logic - Votiro App

## Description

This PR has new parser with "threats" field.
More details are present in the README.md file

## Checklist

- [x] Changes follows the best practices from the given [docs](https://docs.google.com/document/d/1xfYfruru0RFWOH23GRrRzosSlepJUTcakLFHLHdpEtc/edit?usp=sharing).
- [x] Updated CHANGELOG.md.
- [x] Ran unit tests locally.
- [x] Updated screenshots/sample logs if any.

### CODE REVIEW

**Comment by sambhrant-metron** [comment]
hi@sumo-apps-team and team,
Can you please help us review this PR,
Thanks!

**Comment by sambhrant-metron** [comment]
hi @sumo-apps-team and team,
Can you please review this PR,
Thanks!

**Comment by sambhrant-metron** [comment]
hi @sumo-apps-team and team,
Can you please review this PR,
Thanks!

**Comment by JKashyap96** [comment]
This will be prioritised soon, reviewed and merged. Thanks for the patience! @sambhrant-metron

**Review by ankitgoelcmu — APPROVED** [review]
LGTM

**Pull request merged**
