### PR TITLE
Sumo Logic - Votiro App

### PR DESCRIPTION
**Pull request by saurabh-metron**
# PR Details

This is the new Sumo Logic - Votiro App

## Description

This is a new App
More details are present in the README.md file

## Checklist

- [x] Changes follows the best practices from the given [docs](https://docs.google.com/document/d/1xfYfruru0RFWOH23GRrRzosSlepJUTcakLFHLHdpEtc/edit?usp=sharing).
- [x] Updated CHANGELOG.md.
- [x] Ran unit tests locally.
- [x] Updated screenshots/sample logs if any.

### CODE REVIEW

**Comment by JKashyap96** [comment]
Will start the review soon.

**Comment by saurabh-metron** [comment]
@sumo-apps-team @sumo-drew 
Hi Team,
Could you please help us review this PR, thanks!

**Comment by saurabh-metron** [comment]
@sumo-apps-team - any updates on the review?
cc: @sumo-drew

**Comment by saurabh-metron** [comment]
Hi @sumo-apps-team - any updates on the review please?
cc: @sumo-drew

**Comment by JKashyap96** [comment]
@ankitgoelcmu Please have a look on this.

**Review by ankitgoelcmu — APPROVED** [review]
LGTM

**Pull request merged**
