### PR TITLE
Sumo-LambdaTest: first checkin

### PR DESCRIPTION
**Pull request by prateeksainilambdatest**
# PR Details

## Checklist

- [x] Changes follows the best practices from the given [docs](https://docs.google.com/document/d/1xfYfruru0RFWOH23GRrRzosSlepJUTcakLFHLHdpEtc/edit?usp=sharing).
- [x] Updated CHANGELOG.md.
- [x] Ran unit tests locally.
- [x] Updated screenshots/sample logs if any.

### CODE REVIEW

**Comment by sumo-drosiek** [comment]
cc: @SumoLogic/sumoappdev

**Comment by prateeksainilambdatest** [comment]
Hi @sumo-apps-team 
Any update here? It's been a week already.

**Comment by JKashyap96** [comment]
@prateeksainilambdatest We require information/documentation regarding how logs are being sent to Sumo, basically the integration process. Reference: https://github.com/SumoLogic/sumologic-public-partner-apps/tree/master/Gigamon_HAWK#collect-logs-for-gigamon_hawk

**Comment by JKashyap96** [comment]
@prateeksainilambdatest Also only a few panels are getting lit up with the logs provided, need more logs to test the working of all panels.
Screenshot 2022-09-07 at 12 15 09 PM
a2a96f3-8ddb-4466-99cc-a210f9d2ec9d.png">

**Comment by prateeksainilambdatest** [comment]
@JKashyap96 You can find how logs are being sent to Sumo here:
https://www.lambdatest.com/support/docs/sumo-logic-integration/

**Comment by JKashyap96** [comment]
@prateeksainilambdatest Yes working on it. Thanks.

**Comment by JKashyap96** [comment]
Screenshot 2022-09-08 at 4 45 27 PM
Screenshot 2022-09-08 at 4 45 08 PM
These 4 panels are not lighting up, need logs for them. Can you send them? a different file with logs will work. @prateeksainilambdatest

**Review by JKashyap96 — DISMISSED** [review]
LGTM, we can merge

**Review by JKashyap96 — APPROVED** [review]
LGTM

**Pull request merged**
